from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]   # repo root
OUTPUTS_DIR = ROOT_DIR / "outputs"
TB_DIR = OUTPUTS_DIR / "tensorboard"
CHECKPOINTS_DIR = OUTPUTS_DIR / "checkpoints"

OUTPUTS_DIR.mkdir(exist_ok=True)
TB_DIR.mkdir(exist_ok=True)
CHECKPOINTS_DIR.mkdir(exist_ok=True)

M = 6
N = 24
UTILITY = 0.7
BASE_SEED = 123
N_ENVS = 8

ARRIVAL_STEP = 0.05
ARRIVAL_SEED = 2
LAM_MAX = 0.6
ALPHA_DIRICHLET = 1.0

MAX_STEPS_PER_RUN = 1000
MAX_QUEUE_LENGTH = 100
LAMBDA_COLLISION = 0.0

LEARNING_RATE = 7e-4
N_STEPS = 256
BATCH_SIZE = 512
N_EPOCHS = 10
ENT_COEF = 0.001
VF_COEF = 0.5
MAX_GRAD_NORM = 0.5
CLIP_RANGE = 0.2
GAMMA = 0.99

TOTAL_TIMESTEPS = 600_000
ADDITIONAL_TIMESTEPS = 150_000

EVAL_FREQ = 1024
EVAL_T = 1000
EVAL_EPISODES = 500
EVAL_SEED = 123